compatibility_date = "2023-10-16"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
name = "r2-webdav"

# Remove this line:
# node_compat = true

[[r2_buckets]]
binding = "bucket"
bucket_name = "webdav"

[observability]
enabled = true
head_sampling_rate = 1